// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/shichen437/live-dog/internal/app/admin/dao/internal"
)

// internalPushChannelWebDao is internal type for wrapping internal DAO implements.
type internalPushChannelWebDao = *internal.PushChannelWebDao

// pushChannelWebDao is the data access object for table push_channel_web.
// You can define custom methods on it to extend its functionality as you wish.
type pushChannelWebDao struct {
	internalPushChannelWebDao
}

var (
	// PushChannelWeb is globally public accessible object for table push_channel_web operations.
	PushChannelWeb = pushChannelWebDao{
		internal.NewPushChannelWebDao(),
	}
)

// Fill with you ideas below.
