// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/shichen437/live-dog/internal/app/live/dao/internal"
)

// internalLiveManageDao is internal type for wrapping internal DAO implements.
type internalLiveManageDao = *internal.LiveManageDao

// liveManageDao is the data access object for table live_manage.
// You can define custom methods on it to extend its functionality as you wish.
type liveManageDao struct {
	internalLiveManageDao
}

var (
	// LiveManage is globally public accessible object for table live_manage operations.
	LiveManage = liveManageDao{
		internal.NewLiveManageDao(),
	}
)

// Fill with you ideas below.
