// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/shichen437/live-dog/internal/app/live/dao/internal"
)

// internalMediaParseDao is internal type for wrapping internal DAO implements.
type internalMediaParseDao = *internal.MediaParseDao

// mediaParseDao is the data access object for table media_parse.
// You can define custom methods on it to extend its functionality as you wish.
type mediaParseDao struct {
	internalMediaParseDao
}

var (
	// MediaParse is globally public accessible object for table media_parse operations.
	MediaParse = mediaParseDao{
		internal.NewMediaParseDao(),
	}
)

// Fill with you ideas below.
