// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/shichen437/live-dog/internal/app/live/dao/internal"
)

// internalRoomInfoDao is internal type for wrapping internal DAO implements.
type internalRoomInfoDao = *internal.RoomInfoDao

// roomInfoDao is the data access object for table room_info.
// You can define custom methods on it to extend its functionality as you wish.
type roomInfoDao struct {
	internalRoomInfoDao
}

var (
	// RoomInfo is globally public accessible object for table room_info operations.
	RoomInfo = roomInfoDao{
		internal.NewRoomInfoDao(),
	}
)

// Fill with you ideas below.
