// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/shichen437/live-dog/internal/app/live/dao/internal"
)

// internalStatDailyDao is internal type for wrapping internal DAO implements.
type internalStatDailyDao = *internal.StatDailyDao

// statDailyDao is the data access object for table stat_daily.
// You can define custom methods on it to extend its functionality as you wish.
type statDailyDao struct {
	internalStatDailyDao
}

var (
	// StatDaily is globally public accessible object for table stat_daily operations.
	StatDaily = statDailyDao{
		internal.NewStatDailyDao(),
	}
)

// Fill with you ideas below.
